### ISSUE TITLE
Items "jump" when removed from isotope instance

### ISSUE THREAD

**Issue by MintyOrb** [David-Desmaisons/Vue.Isotope#24] opened 2017-02-21 15:53 UTC
In the isotope remove example [seen here](http://isotope.metafizzy.co/methods.html#remove) the removed element shrinks and fades and the layout is then rearranged. In [this test example](http://vue-iso-remove.surge.sh/#/e) clicking a word adds it to a different isotope instance and removes it from the current one. Adding the elements seems to work just fine, however, the removal is not smooth. 

Any thoughts on what could be causing this?

**Comment by David-Desmaisons** [comment] 2017-02-21 16:09
Hello @bornytm , this looks a very promising example usage of vue-isotope.

I guess I have an idea what the problem is. I will investigate it later today.

**Comment by David-Desmaisons** [comment] 2017-02-21 16:27
I have some tests with simplier example and everything seems ok. Could you make a short animated gif with the "unsmooth" animation on your page please?

**Comment by MintyOrb** [comment] 2017-02-21 17:23
[Sure thing](http://i.imgur.com/EppA213.gif). I'm not sure it matters, but I'm updating the arrays with a function like this:
```
removeFrom: function(item, theArray){
      for( i=theArray.length-1; i>=0; i--) { 
          if( theArray[i].name == item.name) theArray.splice(i,1);
      }
```
At first I was using
```
this.selected = this.selected.filter(function(el) { 
           return el.name !== item.name;
       });
```
which I thought might be causing problems since it makes a new object instead of using the existing one.

**Comment by David-Desmaisons** [comment] 2017-02-24 12:13
I am not sure about this. Did you try to play around with layout options to see if there a configuration that may resolve the issue?

Otherwise please create a jsfidle with the problem so I can investigate.
Thanks,

**Comment by MintyOrb** [comment] 2017-02-25 03:26
No luck in playing with the layout options :/ [Here's a fiddle with the issue](https://jsfiddle.net/1a32bzm5/32/). Clicking the element adds it to the second isotope instance and removes it from the current one.

Thanks David.

**Comment by David-Desmaisons** [comment] 2017-02-25 15:00
@bornytm  It seems that this is the original isotope example. did you paste the wrong link?

**Comment by MintyOrb** [comment] 2017-02-25 17:48
@David-Desmaisons I used the original as a base- the link I shared has two isotope instances and a function that adds elements from one to the other when clicked.
```
addToList: function(item, to, from){
    to.push(item) // add to
    for( i=from.length-1; i>=0; i--) { // remove from
            if( from[i].name == item.name) from.splice(i,1);
        }
    },
```

**Comment by David-Desmaisons** [comment] 2017-03-15 02:13
Hello @bornytm , it seems that the problem is linked to the animation when removing element. I will investigate.

**Comment by David-Desmaisons** [comment] 2017-03-20 01:49
Hi @bornytm , version 3.0.0rc that I just released contains a fix for this issue

**Comment by David-Desmaisons** [comment] 2017-03-20 01:56
See https://jsfiddle.net/dede89/jm8g2qx7/ for demonstration

**Closed as completed by David-Desmaisons** 2017-03-20 01:56 UTC

**Comment by MintyOrb** [comment] 2017-03-20 03:28
Excellent! This is great David. Thanks :)
